baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo with Gulp starter kit"
theme = "project_theme"

[taxonomies]
  category = "category"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pre = "<i class='fa fa-heart'></i>"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    identifier = "pages"
    name = "Pages"
    pre = "<i class='icon-arrow-down'></i>"
    weight = 3
  [[menu.main]]
    parent = "pages"
    name = "Category page"
    url = "/category/"
  [[menu.main]]
    parent = "pages"
    name = "Error 404"
    url = "/404.html/"

[params]
  title = "Hugo with Gulp starter kit"